### ISSUE TITLE
Add default values to ELK_VERSION

### ISSUE THREAD

**Issue by gotjoshua** [dcomposed/elk#2]
to ensure that the repo can be cloned and upped without modification.

**Comment by gotjoshua** [comment]
Using [variable substitution syntax](https://docs.docker.com/compose/compose-file/#variable-substitution) in the docker-compose file:
eg:
```
build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION:-5.6.3}
```
This will pass the $ELK_VERSION variable into the Dockerfile if it exists and is not empty, otherwise it will default to 5.6.3. The stack will then be ready to clone and up without modification.

Fixed in https://github.com/dcomposed/elk/commit/8b7977f33083329a2e3a2744d6c3f68a684d4c7e
